### ISSUE TITLE
Front-end "forgets" who you are

### ISSUE THREAD

**Issue by QuintS** [skylines-project/skylines#1042]
Wait long enough and the front-end "forgets" who you are:
Profile drop-down disappears:
![screenshot from 2018-08-01 20-24-22](https://user-images.githubusercontent.com/7008703/43541083-d04b9d0c-95c9-11e8-80e8-3cc5f90974dd.png)
Flights/Stats only general:
![screenshot from 2018-08-01 20-24-59](https://user-images.githubusercontent.com/7008703/43541212-19f2e820-95ca-11e8-8144-92247ed1863b.png)

F5 and it's back. Had this happen on both Chrome 68.0.3440.75 on Ubuntu 18.04 (running uBlock, but no elements on SkyLines blocked) and Chrome 68.0.3440.70 on Android 8.0.0.

**Comment by Turbo87** [comment]
thanks for reporting. I had noticed that too, but it seemed hard to reproduce locally so I haven't had a chance to fix it yet.

**Comment by QuintS** [comment]
After new "splash screen" login, issue not seen anymore.
