### ISSUE TITLE
IGC upload shows straight  line to Africa

### ISSUE THREAD

**Issue by mkauzlar** [skylines-project/skylines#1397]
Uploading the attached IGC shows a straight line on the map:

https://skylines.aero/flights/101343

[2019-03-09-xcm-2hx-01.igc.zip](https://github.com/skylines-project/skylines/files/2982719/2019-03-09-xcm-2hx-01.igc.zip)

**Comment by Turbo87** [comment]
your file contains `B1243250050014N01323174EA00879009390080999951731001-0014` at some point. you should contact your flight recorder manufacturer about this and ask them why they record GPS fixes that don't make any sense 😉 

right above that line, it says `LXCMGPS-NODATA`, so I'm assuming the flight recorder lost GPS information. in that case, it is supposed to set the validity flag from `A` to `V`, and then SkyLines would just ignore that fix. for some reason the Oudie doesn't seem to do that though 🤷‍♂️

**Comment by mkauzlar** [comment]
Right, the thing is that I used https://www.soaringlab.eu/viewer.php to view the file and there it's displaying correctly
