### ISSUE TITLE
No Wingmen

### ISSUE THREAD

**Issue by trayz777** [skylines-project/skylines#1529]
There are no Wingmen shown in the Wingman-Tab. 
Issue persists on multiple devices and accounts.

**Comment by Turbo87** [comment]
hmm, interesting. this seems to have broken between 2019-05-24 and 26:

- https://skylines.aero/flights/104597#tab-wingmen works fine
- https://skylines.aero/flights/104739#tab-wingmen is empty

I don't know yet what specifically could have caused this 🤔

**Comment by trayz777** [comment]
You are right, seems to be broken since 2019-05-25

**Comment by Turbo87** [comment]
I restarted the corresponding service that calculates that data. It's currently working through the queue and the data should be available again soon.
