### ISSUE TITLE
Handicaps for SGS 1-26 and SGS 1-34 for gliders are not being applied

### ISSUE THREAD

**Issue by Johnb1957** [skylines-project/skylines#1664]

**Comment by Turbo87** [comment]
what handicap factors do those planes have?

**Comment by Johnb1957** [comment]
Tobias,

Thanks for the quick response. The SGS 1-26 handicap is 1.60, the SGS 1-34
1.18. There are still quite a few 1-26 pilots competing in their own class
here in the US. So even though it's extremely low performance there are a
number of good flights every year.

Thanks again and all the best,

John

Here's the list of handicaps for Schweizer gliders from the SSA (handicap
on the far right) -

Schweizer SGS 1-21 15.5 720 1.468
Schweizer SGS 1-23 13.4 650 1.38
Schweizer SGS 1-23B 13.4 650 1.38
Schweizer SGS 1-23C 13.4 650 1.38
Schweizer SGS 1-23D S 15 744 1.3
Schweizer SGS 1-23E 16.1 744 1.3
Schweizer SGS 1-23F 16.1 744 1.3
Schweizer SGS 1-23G 16.1 744 1.3
Schweizer SGS 1-23H 16.1 750 1.24
Schweizer SGS 1-23H-15 S 15 750 1.26
Schweizer SGS 1-24 16.9 785 1.22
Schweizer SGS 1-26A 12.2 575 1.65
Schweizer SGS 1-26B 12.2 575 1.65
Schweizer SGS 1-26C 12.2 575 1.65
Schweizer SGS 1-26D 12.2 695 1.6
Schweizer SGS 1-26E 12.2 695 1.6
Schweizer SGS 1-29 S 15 750 1.233
Schweizer SGS 1-34 SF 15 780 1.18
Schweizer SGS 1-34R SR 15 800 1.17
Schweizer SGS 1-35 RC 15 660 1.013
Schweizer SGS 1-35 Club F 15 685 1.07
Schweizer SGS 1-35A RC 15 840 0.975
Schweizer SGS 1-36 14.1 710 1.314
Schweizer SGS 2-22 13.1 900 2
Schweizer SGS 2-22A 13.1 900 2
Schweizer SGS 2-22C 13.1 900 2
Schweizer SGS 2-22E 13.1 900 2
Schweizer SGS 2-32 17.4 1350 1.25
Schweizer SGS 2-33 15.5 1080 1.84
Schweizer SGS 2-33A 15.5 1080 1.84
Schweizer SGU 1-20 13.1 628 2.01
Schweizer SGU 2-12 16.6 1200 1.54

**Comment by Turbo87** [comment]
I finally had time to update the handicaps for the existing types. Let me know if you see any other issues :)

**Comment by Johnb1957** [comment]
Thank you Tobias. Even better I see you got other Schweizer models in -
I'll have to start flying an SGS 2-33!

All the best,

John
