### ISSUE TITLE
Skylines API gives me 404

### ISSUE THREAD

**Issue by ekurutepe** [skylines-project/skylines#1813]
I'm trying to access the API under `https://api.skylines.aero/` as specified in https://gist.github.com/Turbo87/72d73a548dbf953e1f5e 

I'm using Basic Auth and trying to `GET /user` but receive: `404 Site api.skylines.aero is not served on this interface`

Is the API not active or am I missing something?

**Comment by Turbo87** [comment]
👋 

unfortunately, the API mentioned in that Gist has not been implememented (yet?). we do have and use an API, but it is currently somewhat custom and should not be considered public/stable. that being said, the current API does work and hasn't changed much for quite some time, so it might be okay to just use it for now.

**Comment by ekurutepe** [comment]
Can you please point me towards that API? 

I'm working on an iOS app to grab flights from the SD card and upload them to Skylines.

**Comment by ekurutepe** [comment]
@Turbo87 pinging this up. Can you give me access to the current API?

**Comment by Turbo87** [comment]
sorry, for the delay. unfortunately, there is not much documentation for the current API. the API implementation can be found in https://github.com/skylines-project/skylines/tree/master/skylines/api/views, with some corresponding API tests in https://github.com/skylines-project/skylines/tree/master/tests/api/views.

**Comment by ekurutepe** [comment]
thank you, my python is rusty but it's a great start. 

I kinda thought I'd need some kind api key or something. But it's better this way.
