### ISSUE TITLE
.igc file rejected due to missing date.

### ISSUE THREAD

**Issue by Zaphod2112** [skylines-project/skylines#1878]
My .igc file from my Oudie 2/SeeYou was repeatedly rejected due to a "missing date".  The file works fine with SeeYou mobile and SeeYou Cloud and was also posted to the OLC website with out an issue.

Thanks

**Comment by Turbo87** [comment]
can you share the file so that we can try to reproduce it?

**Comment by Zaphod2112** [comment]
I've attached the file.  Thank you for taking a look at it.

Doug Hingst

**Comment by Turbo87** [comment]
hmm, I don't see the file anywhere? how did you attach it?

**Comment by Zaphod2112** [comment]
I show that it was attached to the email.  I will resend it from my computer.  Here’s a screenshot from my phone showing the attachment.

**Comment by Zaphod2112** [comment]
File should be attached.

**Comment by Zaphod2112** [comment]
Hi,  

It looks like the Skylines website has been down for several days.  Will it be up again soon?

Thanks,

Doug Hingst 

Sent from my iPhone

**Comment by Turbo87** [comment]
@lordfolken 👆
