### ISSUE TITLE
Unknown glider type

### ISSUE THREAD

**Issue by bomilkar** [skylines-project/skylines#1899]
I'm flying a "Discus 2cFES 18m" and would like to upload my flights with the correct type identification. Just to be open and hones.
The closes type I can find is "Discus 2cT 18m". So I'm using this type for now.
Can somebody add  "Discus 2cFES 18m" to the list, please?

**Comment by Turbo87** [comment]
@bomilkar sorry for the delay. it's added to the database now :)

**Comment by bomilkar** [comment]
Thanks @Turbo87 !
I confirm it works:
https://www.skylines.aero/flights/120793
