### ISSUE TITLE
Upload Flight: Aircraft type is not selectable

### ISSUE THREAD

**Issue by ubx** [skylines-project/skylines#1992]
Uploading a flight, is not possible to choose the aircraft type.

**Comment by Turbo87** [comment]
hmm... I'm having a hard time reproducing the issue. It seems to work fine on my side. Can you give more information on what went wrong?

**Comment by ubx** [comment]
I can reproduce it with this file:
[2020-07-07-TRI-XCE-01.zip](https://github.com/skylines-project/skylines/files/4892663/2020-07-07-TRI-XCE-01.zip)
