### ISSUE TITLE
 Live Tracking not working with XCSoar

### ISSUE THREAD

**Issue by ubx** [skylines-project/skylines#2215]
Since some days, I can't see my live tracks on the server. I'm using XCSoar 6.8.17-Android as a tracker. BTW same result with SkyLines Tracker, which uses DNS for address resolution (skylines.aero).

But I'm confused to see some other users live tracks.

**Comment by Turbo87** [comment]
hmm, the third option to use live tracking is using an app that uses the LiveTrack24 protocol, but I'm surprised that the "SkyLines Tracker" is not working. looks like something is wrong and the UDP packets are not arriving at the server.

@lordfolken do you know if anything changed regarding firewall rules or something like that?

**Comment by FlyDubbo** [comment]
I have had similar issues, with none of the keys I use working on any device, using XCSoar of Skylines Tracking App.
I have also been able to see a few others, a couple I know and interestingly they have both been using Iphones and FlySkyHigh.

**Comment by lordfolken** [comment]
I thought it was working because I saw traffic. 
The firewall rule only had tcp enabled for the forward. Now udp is also added, and i see a couple of more traffic fixes.

**Comment by lordfolken** [comment]
@ubx Please check that it works now and close the ticket if so.

**Comment by ubx** [comment]
It works! Thanks.

**Comment by lordfolken** [comment]
@ubx jetzt weis i au wo de lüthi deheime isch. ;)

**Comment by ubx** [comment]
@lordfolken ja genau, wenn er nicht fliegen kann sitzt er da am compi.

**Comment by FlyDubbo** [comment]
Many thanks for you fix.
Regards
Phillip
