### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#226]
Since Skylines is promoted as an Open Data project, we should offer our data in form of a public API. We already offer unimportant things like airports and airspace for the map interactivity, but neither of them is documented so far.

This issue should be used to track all activities related to this effort.
## Key Points
- The API should be reachable through https://www.skylines-project.org/api/ or later https://api.skylines-project.org (SSL certificate is only valid for www subdomain).
- The API is JSON based. Other representations can optionally be added.
- The API code should be used to render the server-side templates if possible. The code in `frontend.views` should use the code in the `api` package, just like the code in `api.views` exposes most of that API to the public.
- It should be possible to create a full-featured JS one-page app that uses the API. Same for possible mobile apps, i.e. Android and iOS.
- The API should be versioned, but it should stay backwards compatible as far as ever possible.
- The API should allow apps like XCSoar or iGlide to upload and publish IGC files directly from the app.
## Tasks
- [ ] Document API endpoints with [Sphinx](http://sphinx-doc.org/) (and [sphinxcontrib.httpdomain](http://pythonhosted.org/sphinxcontrib-httpdomain/))
- [x] `/api/airports`
- [x] `/api/airspace`
- [x] `/api/waves`
- [ ] `/api/events`
- [ ] `/api/flights`
- [ ] `/api/users`
- [ ] `/api/clubs`
- [ ] `/api/files`
- [ ] `/api/tracking`
- [x] `/api/search`
- [x] Implement HTTP BasicAuth and/or OAuth for authenticating with the API
## Examples

A list of well documented public APIs:
- [GitHub](http://developer.github.com/v3/)
- [Twitter](https://dev.twitter.com/docs/api/1.1)

**Comment by GliderGeek** [comment]
@Turbo87: i would really like to help working on issue #236 and thus the /api/flights endpoint. any suggestions where i might start?

**Comment by Turbo87** [comment]
yes, basically all the existing API endpoints are example of how or how not to do it. the truth is that I'm not sure yet either what the best way is for us to write these API handlers... the whole API should be considered experimental at this point and once we actually consume it somewhere we can figure out if how we built it actually makes sense.

**Comment by Turbo87** [comment]
closing this as our Ember.js frontend is now entirely powered by an API. that API might not be public/stable yet, but the short-term goal was achieved.
