### ISSUE TITLE
[Question] Add container config for VSCode

### ISSUE THREAD

**Issue by vicb** [skylines-project/skylines#2311]
Hey @Turbo87,

VSCode make it super easy [to develop code in a Docker env](https://docs.microsoft.com/en-us/learn/modules/use-docker-container-dev-env-vs-code/2-use-as-development-environment).

Basically you can connect to a container and work as it you were working on your local env.

If you think it is valuable, I could submit a PR to:
- remove the vagrant files,
- add the VSCode config files,
- add some doc on how to use VSCode for dev.

This is the environment I use for dev and it's quite easy and powerful.

If there is a dummy proof (I'm the dummy here) env for development it could only ease the contributions.

Let me know what you think.

**Comment by Turbo87** [comment]
As you may have seen, I started adding a Docker based setup in #2306 to replace some parts of the CI pipeline. I already have it half working as a dev environment too, but I'm not entirely done and still figuring some things out.

I personally don't use VSCode that much and it looks like the solution in that link would *only* work for VSCode, while something based on e.g. docker-compose could essentially work for all editors.

so yes, I think Vagrant could/should/will probably be replaced by Docker soon, but ideally using a solution that also works for other editors.

**Comment by vicb** [comment]
The VSCode config I have basically builds on your `docker-compose.yml` (I had almost the same with less flexibility).

Basically the PR would be:
- adding a .devcontainer folder with 2 simple files,
- adding a doc file with details on how to setup VSCode and launch the tests,
- deleting old Vagrant config/docs.

I think it's the best of both world: devs that are the most familiar with docker could use the `docker-compose.yml`. Devs that are less comfortable with Docker could just use VSCode without having to understand how things work underneath.

Up to you, let me know.

**Comment by vicb** [comment]
https://github.com/skylines-project/skylines/compare/master...vicb:vscode/config is what the VSCode config looks like.

That's not much to have a great dev environment.

**Comment by Turbo87** [comment]
I see. I didn't know it was compatible with docker-compose.

I'm fine with adding those files if you think that they would be useful, but: 

- I think a README in that folder that explains them or points to the other docs you mentioned would be helpful and
- since I personally won't be using this setup I can't properly maintain those files so it would be up to you or other contributors to keep them up-to-date

one other question though: what is the advantage of using your setup over using docker-compose directly? just the UI integration? since the existing container mounts the source code the file editing functionality inside the container seems less necessary to me, but maybe I'm missing something 🤔

**Comment by vicb** [comment]
> I think a README in that folder that explains them or points to the other docs you mentioned would be helpful and

I was thinking about a DEVELOPER.md at the root but it could also go into that folder.
Let me know you preference.

> so it would be up to you or other contributors to keep them up-to-date

Sure I can maintain it.

> one other question though: what is the advantage of using your setup over using docker-compose directly?

1) I think if you tell some developers that they need to use Docker, they would run away screaming ;)
2) you can have your own dev environment in VSCode. That is no need to manually launch docker, your own set of VSCode extensions for that project, ...

I agree you can do without this layer of sugar but I think it's easy and simple so why not ?
