### ISSUE TITLE
Live Tracking: View different flights simultaneously

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#232]
> In Skylines we have the option to pin flights and to view them simultaneously.
> 
> I think this would be also a nice feature for Live Tracking, especially for competitions.
> 
> Imported from http://bugs.xcsoar.org/ticket/2223

**Comment by utwig** [comment]
I think that this idea could be developed even further: Have an option to see all live flights on the map. Somewhat similar as the Open Glider Network, but without the need of OGN receiver coverage.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.

**Comment by Harry-R** [comment]
Creating public visible groups of live tracks / pilots would be a very cool feature for competitions, like announced on the [skylines](https://skylines.aero/) front page. Maybe with an expiration date, so that the group gets deleted automatically after the competition.
