### ISSUE TITLE
Password reset on skylines.aero doesn't send the email

### ISSUE THREAD

**Issue by mkauzlar** [skylines-project/skylines#2478]
Using https://skylines.aero/users/recover to recover the password it says that the reset email was sent but it never arrives.

**Comment by Turbo87** [comment]
@lordfolken do you have time to look into this?

**Comment by lordfolken** [comment]
I reconfigured the relay host to a new smtp server.

**Comment by Turbo87** [comment]
awesome, thank you @lordfolken! :)
