### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by vicb** [skylines-project/skylines#2489]
At least since this morning.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/248818/230741231-b50fd50f-8db6-4282-a717-a401303a2a9f.png">

**Comment by vicb** [comment]
Wahoo still offline.
That's a serious outage!

Not meaning any offense but is skylines still maintained? If so would migrating to the cloud help?

**Comment by vicb** [comment]
Is there something I can do to help solve this faster?

**Comment by vicb** [comment]
If it fits on an e2-micro then it's [free](https://cloud.google.com/free/docs/free-cloud-features#compute) 

Specs are [here](https://cloud.google.com/compute/all-pricing#e2_sharedcore_machine_types)

I use it for flyxc.app and it works well

**Comment by lordfolken** [comment]
Its fixed.

**Comment by lordfolken** [comment]
Specs:
              total        used        free      shared  buff/cache   available
Mem:           3891        1746         153         230        1991        1669
Swap:          2047         557        1490

Disk: 
/dev/vda1       305G  250G   43G  86% /

CPU: presently 4 cores (There is a PostGresSQL db) 

Traffic:
                      RX          TX   │                      RX          TX   │                      RX          TX   │                      RX          TX   │                      RX          TX
 Bytes             11.90GiB    67.40GiB

In 18:52:17 up 69 days,  9:05,  1 user,  load average: 0.23, 0.35, 0.29

What would help is to containerize skylines. That way I wouldn't be dependent on a vm. (The vm is in a cluster.. but the proxy server in front of it somehow died.. still investigating. And i didn't notice as it drowned in the errors from monitoring...)

**Comment by lordfolken** [comment]
As for payment. The weglide".org" guys also charge quite successfully. It should be possible to add payed features.
