### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by mkauzlar** [skylines-project/skylines#2493]
This site can’t be reached
https://skylines.aero/ is unreachable.
ERR_ADDRESS_UNREACHABLE

**Comment by dahlmo** [comment]
I noticed the same. Is it @Turbo87 who's hosting it? Whoever it is, they're champs for providing it ad-free and AFAIK it's stable 🙌

**Comment by vicb** [comment]
Looks like it's up again.
Thanks to whoever.

**Comment by lordfolken** [comment]
People seem to only care when its down. I should pull the plug more often. Anyway, network lag group that didnt work as expected, destroyed the quorum of the cluster.
