### ISSUE TITLE
Frontend (skylines.aero) track.php (!) location?

### ISSUE THREAD

**Issue by dahlmo** [skylines-project/skylines#2494]
I thought the frontend was Python/Flask, but I also see that the app performs requests towards `skylines.aero/track.php` e.g. a PHP endpoint. I can't find this file anywhere within the repository – is the frontend hosted somewhere else or not open source at all?

**Comment by Turbo87** [comment]
see https://github.com/skylines-project/skylines/blob/ce68ee280af05498b3859fc2c199b08043ad58a9/skylines/frontend/views/livetrack24.py#L206
