### ISSUE TITLE
SkyLines app on Android14 Pixel6a

### ISSUE THREAD

**Issue by nokkerlcad** [skylines-project/skylines#2499]
Hi - me and at least another user have had SkyLines tracking app stop working on Android14 on a Pixel6a. I am no programmer - just using the app. App runs fine on other phone same settings.

Cheers

**Comment by Turbo87** [comment]
The only official Skylines tracking app is XCSoar. If you are using a different app then you should probably report this problem to the developers of that app :)

**Comment by nokkerlcad** [comment]
Oh I see, I thought these were the same ppl. Cheers
