### ISSUE TITLE
Website down since yesterday 

### ISSUE THREAD

**Issue by cyberorg** [skylines-project/skylines#2503]
Hi, https://skylines.aero is down since yesterday, any estimate of time when it is expected to be up?

“ The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.”

Thanks

**Comment by vicb** [comment]
I just ping @Turbo87 by email.

**Comment by cyberorg** [comment]
Is there no quicker way or no one else has access to the server?

**Comment by Turbo87** [comment]
only @lordfolken has direct access to the server

**Comment by lordfolken** [comment]
Back up. Failed ceph migration. Will buy more storage.
