### ISSUE TITLE
Comments Display

### ISSUE THREAD

**Issue by tilpa** [skylines-project/skylines#257]
A long URL expands the comments area to behind map:
https://www.skylines-project.org/flights/27025/

**Comment by kerel-fs** [comment]
Bug still existent, but fix available.

URL to check when it's fixed:
https://skylines.aero/flights/27025/#tab-comments

Firefox 60.0.1
![image](https://user-images.githubusercontent.com/10089607/40304438-0953e674-5cf7-11e8-9e27-6d86d13e0f49.png)

Chromium Version 66.0.3359.181 (Official Build) Arch Linux (64-bit)
![image](https://user-images.githubusercontent.com/10089607/40304587-98571c92-5cf7-11e8-9cb7-30110b942e15.png)
