### ISSUE TITLE
Score: Possibility to choose method

### ISSUE THREAD

**Issue by Adrien81** [skylines-project/skylines#285]
A default OLC method is used for scoring in SkyLines, I think there should be a user setting to choose among the same rules allowed by XCSoar.
I don't think there is a need for 2 options, one for "Flights" page, and one for "show page". What do you think?

cf. XCSoar source:src/Engine/Contest/Solvers/Contests.cpp
  _T("OLC Sprint"),
  _T("OLC FAI"),
  _T("OLC Classic"),
  _T("OLC League"),
  _T("OLC Plus"),
  _T("XContest"),
  _T("DHV-XC"),
  _T("SIS-AT"),
  _T("FFVV NetCoupe"),
  _T("DMSt"),

**Comment by Adrien81** [comment]
That issue is independent from a contest feature (as in competition scoring).

I understand a SkyLines scoring shall be consistent for all users.

The choice of "OLC Classic" (6 legs apparently, not 5) seems indeed biased by its wide use in Germany. For international use, an FAI rule would have been more adequate (see sporting code section 3). And of course, changing the default ranking rule now would be a mess. So be it, the general ranking is based on an OLC rule, that's legacy now.

So I change my mind from the initial demand:
The "Overview" menu should stick to general scoring rule (+ triangle??), but for "local" use, I believe the "Distance" in "Legs" menu should be user selectable with the same list available in XCSoar. Triangle would automatically be one item of the list: "OLC FAI" (*).

FYI, most French pilots optimize their flights according to 4 legs only, not 6. So a widget with km based on OLC rule is meaningless.

(*) Isn't the name misleading? "FAI triangle" would be better I guess, but that's at XCSoar level.

**Comment by Adrien81** [comment]
Hi, I made a presentation of SkyLines at my club and can only confirm the need for  a "local" setting of the "Distance" optimization.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
