### ISSUE TITLE
Wingmens displayed in flight after new flight selection

### ISSUE THREAD

**Issue by matthiasluethi** [skylines-project/skylines#300]
After a wingmen is selected (which I find is a bit hidden) to be shown in a flight, it is still present if a go back and select a totally different flight from the flight list. At some point this is fine (analyzing flights from the same day in the same region) but if I select a flight from a totally different date and/or region this is useless.

**Comment by Turbo87** [comment]
closing as this seems to work as designed for now. we might change the design in the future though.
