### ISSUE TITLE
Add New Zealand Airspace

### ISSUE THREAD

**Issue by nallison** [skylines-project/skylines#316]
Create an updated whole NZ airspace file for Skylines, preferably from the most recent NZANR with target release date by 1 Nov 14.

For Skylines to display airspace, each country may only have a single file containing all the airspace to display.  Currently limited area airspace files (mainly for local contests) and/or out of date files are published on World Wide Turnpoint exchange http://soaringweb.org/Airspace/AU/HomePage.html

**Comment by Turbo87** [comment]
@nallison @frankvdh what is the current state of this? is there a way for us to display the data without any legal issues?

**Comment by frankvdh** [comment]
Hi Turbo,

See http://www.aip.net.nz/ in particular 3a

"You may not do anything with or to the Material that is not expressly
authorised by the CAA. In particular (but without limitation) you may not
 extract, copy, reproduce, modify, adapt, distort or vary the Material by
any means or in any form other than for your personal use;"


I think this is clear... I can't share the airspace with you :( CAA sells
these rights to (e.g.) AirNav Pro for a great deal of money, and with a
requirement to have huge amounts of insurance. I don't see any point in
even applying for authorization.

However, Neil says that Gliding NZ has a good relationship with CAA, and
maybe they can get authorization? If they can, I'm happy to do it.

Frank

**Comment by Turbo87** [comment]
hmm I see... I'll close this issue for now, but feel free to reopen once you've found a way to make this work.

**Comment by nallison** [comment]
Hi Tobi and Frank,

GNZ has a letter approving Gliding NZ "to the access the NZANR data 
to provide specialist [sic] use airspace files free of charge to its 
pilots".  To follow the spirit of this letter I think we'll need to 
publish at least a link to the airspace on the GNZ website: 
http://gliding.co.nz/pilots/pilot-resources/airspace-files/
Of course all GAA and sport pilots and those using XCSoar can get 
and use the files from that link. 

IIRC, the Skylines airspace file is only read at server restart 
rather than being a "live" config file so we should really decide 
and fix our airspace URL to minimise changes to the Skylines setup?  

Ideally we need a fixed location with a URL that Skylines can point 
to and that Frank and/or I can "upload" airspaces files to.  A 
couple of years ago we trialled using a www.box.com address: 
https://app.box.com/ats-xcsoar

What is missing is me arranging with GNZ and the GNZ webmaster for a 
suitable location and/or linking to our preferred location.  I'll 
email them this week.

Frank, do you have any suggestions for a hosting site?  Maybe a 
google docs, dropbox, box.com  or some other cloud service?  

Tobi, do you have any suggestions?

Sorry for my slow replies and not doing anything on this for a while 
as I've been too busy with a design project for a client.

Kind regards
Neil
skype: neil_allison
IRC: nallison
m: +64 21 765 884


On 9 May 2015 at 10:59, frankvdh wrote:

Date sent:	Sat, 09 May 2015 10:59:14 -0700

**Comment by Turbo87** [comment]
@nallison for clarification: the airspace import is currently a manual process. once triggered it runs through a [list of airspace files](https://github.com/skylines-project/skylines/blob/master/mapserver/airspace/airspace_list.txt) and imports the airspaces into our database.

if you want more recent airspace files in XCSoar you may also update https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json#L116-L122
