### ISSUE TITLE
Requests should be always redirected to https://skylines.aero

### ISSUE THREAD

**Issue by fb** [skylines-project/skylines#364]
It's okay that you can reach the website by using links like https://www.skylines.aero/flights/latest because this is something many people do.

http://skylines.aero/flights/latest --> https://www.skylines.aero/flights/latest
https://skylines.aero/flights/latest --> https://skylines.aero/flights/latest
https://blog.skylines.aero/flights/latest --> https://blog.skylines.aero/flights/latest
https://blog.skylines.aero/flights/latest --> https://www.skylines.aero/flights/latest 

In my opionion, it would be best to redirect, all requests to have https://skylines.aero as base, e.g. https://skylines.aero/flights/latest for my example. www.skylines.aero does not have any atvantage over skylines.aero.

**Comment by Turbo87** [comment]
done
