### ISSUE TITLE
Update Dutch airspace for 2015

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#381]
New airspace can be downloaded, in OpenAir format, at this URL:
https://www.gliderpilotshop.com/databases

**Comment by Turbo87** [comment]
@roeles please also open a PR against https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json. thanks!

**Comment by roeles** [comment]
I suspect that takes me more then twice the effort it takes you, but if you
have no time at all I'm willing to give it a shot.

**Comment by Turbo87** [comment]
should be no effort at all actually. just open the link, click on "edit this file", change the URL, commit the change and create a pull request from the commit. thanks to github that should be relatively straight-forward :)

**Comment by roeles** [comment]
Done... I think :)

**Comment by roeles** [comment]
Eindhoven TMA 1 had an incorrect top height of 3000ft MSL, which was reported here:
http://www.zweefportaal.nl/main/forum/viewthread.php?thread_id=3596&rowstart=0

Following the instructions here:
http://www.zweefportaal.nl/main/forum/viewthread.php?thread_id=3596&rowstart=20#post_25460

I updated the original file and made it available here:
http://spekje.snt.utwente.nl/~roel/EHv15_3c.txt

Please use that file.

**Comment by lordfolken** [comment]
@roeles Do you mind if i change the xcsoar-data-repository url for the netherlands to that url?

**Comment by lordfolken** [comment]
I think i will use the soaringweb url instead.
