### ISSUE TITLE
Club list overview on top of map makes tracks unreadable

### ISSUE THREAD

**Issue by Philippe-P** [skylines-project/skylines#385]
We include a Skylines visualization in our paragliding club, so that people can monitor the whereabouts of our pilots (http://www.augredelair.fr/live-tracking/).
The code we use is:
iframe src="https://www.skylines.aero/tracking/3944,3990,4210,1998,4164,2412,2413,4181,2045,4023,2677,4165,2011,2689,2037,4172/map" width="650" height="600"
The problem is that since a few days, the overview of the list of the club pilots is being displayed when loading Skylines, and thus no live track is visible until we click on the top left  "i" to close that pilot list. Unfortunately, not everybody understands it... 
What about leaving the tracks on and the overview list off by default when opening Skylines?

**Comment by Turbo87** [comment]
closing this in favor of #469 which will solve this use case as well
