### ISSUE TITLE
Sidebar needs Close/Minimize button

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#386]
We've received a few questions on how to close the new sidebar (#375) and it doesn't seem to be intuitive enough to just click on the activated tab.

I would suggest to put something like http://fontawesome.io/icon/caret-left/ on the right side of the sidebar header to make it more intuitive.

**Comment by Philippe-P** [comment]
As suggested elsewhere, a logical solution would be the other way around: leave the (semi-transparent) sidebar closed by default when opening the tracking page, and let users open it if wanted. This way, the sidebar would not obscure the whole map as happens on smaller screens, resulting in quite a few users being not understanding how to access the live-tracking map.

**Comment by Turbo87** [comment]
@Philippe-P that might work for the live tracking page, but not necessarily for the flight details page

**Comment by Adrien81** [comment]
why?
At least on some mobile devices, the default side bar in open mode obscures all the map.
Maybe a short (minimal) set of information in the upper left corner on a transparent background would be enough by default: pilot's name in tracking (+ date for uploaded flights), on a single line
And a button to vertically expand the current sidebar.

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
