### ISSUE TITLE
FAI Triangle calculation wrong?

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#393]
[OLC](http://www.onlinecontest.org/olc-2.0/gliding/flightinfo.html?dsId=4287774) 384km vs [Skylines](https://www.skylines.aero/flights/45780/) 21km

@TobiasLohner any ideas?

**Comment by TobiasLohner** [comment]
Could be a problem due to excessive trace thinning at the final glide...


On 08.05.2015 19:46, Tobias Bieniek wrote:
> OLC 384km
> <http://www.onlinecontest.org/olc-2.0/gliding/flightinfo.html?dsId=4287774>
> vs Skylines 21km <https://www.skylines.aero/flights/45780/>
> 
> @TobiasLohner <https://github.com/TobiasLohner> any ideas?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skylines-project/skylines/issues/393>.
> 

-- 
Der größte Aberglaube der Gegenwart ist der Glaube an die Vorfahrt.
		-- Jaques Tati

**Comment by TobiasLohner** [comment]
The in-depth analysis is only run after publishing the flight. The
latter avoids thinning problems but takes a few seconds to calculate.

On 08.05.2015 19:46, Tobias Bieniek wrote:
> OLC 384km
> <http://www.onlinecontest.org/olc-2.0/gliding/flightinfo.html?dsId=4287774>
> vs Skylines 21km <https://www.skylines.aero/flights/45780/>
> 
> @TobiasLohner <https://github.com/TobiasLohner> any ideas?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skylines-project/skylines/issues/393>.
> 

-- 
Manche Menschen sprechen aus Erfahrung, andere sprechen aus Erfahrung
nicht.
		-- Christopher D. Morley

**Comment by Turbo87** [comment]
that seems to have been the problem. I guess you have triggered the recalculation manually, right?
