### ISSUE TITLE
Unable to delete Flights due to GUI error

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#401]
Hi, 

I cannot delete a duplicate Flight. (One I uploaded from 2 log sources). 
When pressing the delete button from the view, the sub dialog is only partially visible. When in full-screen mode the sub dialog does not show at all.

**Comment by lordfolken** [comment]
![2015-06-01-092921_956x1041_scrot](https://cloud.githubusercontent.com/assets/407371/7908044/01c5dfba-0841-11e5-9902-761196094a60.png)

**Comment by lordfolken** [comment]
This seems to be chrome browser specific. Firefox shows the page without issue.

**Comment by Turbo87** [comment]
I have to admit that this is a known bug, but I haven't had time to debug it myself. I suspect that the modal dialog HTML is inside the sidebar, which has `overflow:hidden` assigned. In theory we would just need to move the dialog code outside of the sidebar, but I'm not sure how the code around there is currently structured as @TobiasLohner has written that part.

**Comment by Turbo87** [comment]
this seems to be resolved by now
