### ISSUE TITLE
Global Pilot statistics are not updated

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#402]
Hello

I just uploaded 10 flights for 2015 and got a 502. The flights seem to have been uploaded, however the global statistics on the pilot page are not current.

**Comment by lordfolken** [comment]
![2015-06-01-093708_956x1041_scrot](https://cloud.githubusercontent.com/assets/407371/7908133/e3d5f9f8-0841-11e5-9214-99540c9c6dab.png)
![2015-06-01-093728_956x1041_scrot](https://cloud.githubusercontent.com/assets/407371/7908134/e3ea844a-0841-11e5-96c2-cb957bfc4a3e.png)

**Comment by Turbo87** [comment]
those flights are not "published" yet (they are written in italic font) and unpublished flights do not count for the statistics
