### ISSUE TITLE
What config to use a LiveTrack 24 client ?

### ISSUE THREAD

**Issue by vicb** [skylines-project/skylines#406]
I have tried the following with Gaggle:
- username = my skylines key,
- url = https://skylines.aero
- password = whatever

Gaggle shows a "unexpected server response" when I start logging.

_I know that Gaggle supports Skylines. Only trying to find the config for a friend who owns an iPhone_

**Comment by Turbo87** [comment]
That should be enough to make it work. I don't use Gaggle so I can't really help you with that. You would have to find out what response Gaggle is expecting. 

SkyLines only supports the first/older version of the LT24 protocol and our own more efficient protocol. If Gaggle expects the newer LT24 protocol this will probably not work.
