### ISSUE TITLE
3D rendering

### ISSUE THREAD

**Issue by nelg** [skylines-project/skylines#414]
3D mode looks like it will be great.  On my desktop, Clicking the 3D button does not work.

It shows the blue flight line, in 3D, with height (can drag view point around), but the background layer just shows black.  I've tried with a range of different layers.  still just appears black.

Details:
Browsers: Firefox ESR 38.3.0 and Google Chrome Version 45.0.2454.101 (64-bit)
OS: 64bit Mageia Linux
Network: IPv4 and IPv6 (dual stack)
Test URL: https://skylines.aero/flights/55387/

Note: 3D support in my desktop works fine, I use other 3D apps.

The web developer console in firefox, shows the following:
<pre>
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. requestNotifier.js:64:0
Use of Mutation Events is deprecated. Use MutationObserver instead. itsalltext.js:766:0
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ skylines-b7fbaf12.js:1:0
Use of Mutation Events is deprecated. Use MutationObserver instead. itsalltext.js:766:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. skylines-b7fbaf12.js:1:0
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create Cesium.js:458:16694
Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture, with a minification filter requiring a mipmap, and is not mipmap complete (as defined in section 3.7.10). Cesium.js:433:10011
"An error occurred in "": Failed to obtain terrain tile X: 1 Y: 0 Level: 0." Cesium.js:420:26831
"An error occurred in "": Failed to obtain terrain tile X: 0 Y: 0 Level: 0." Cesium.js:420:26831
Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture, with a minification filter requiring a mipmap, and is not mipmap complete (as defined in section 3.7.10). Cesium.js:433:10011
Empty string passed to getElementById(). skylines-b7fbaf12.js:1:0
Error: WebGL: A texture is going to be rendered as if it were black, as per the OpenGL ES 2.0.24 spec section 3.8.2, because it is a 2D texture, with a minification filter requiring a mipmap, and is not mipmap complete (as defined in section 3.7.10). Cesium.js:433:10011

</pre>

**Comment by Turbo87** [comment]
hmm... this used to work quite well but I can confirm that I have the same issues now with Chrome on OSX

**Comment by nelg** [comment]
as you've confirmed you've also got the same problem, that's great, because it means the problem is not likely to just be with my setup, but with something the site uses.

Switching to the network call tab in firefox web developer plugin, and looking at the calls being made.  We have some calls to cesiumjs.org, which are returning a 404.  These are:

https://cesiumjs.org/stk-terrain/tilesets/world/tiles/layer.json
https://cesiumjs.org/stk-terrain/tilesets/world/tiles/0/1/0.terrain?v=1.0.0

This seems to me that's where we should start looking.

**Comment by nelg** [comment]
Testing: https://cesiumjs.org/Cesium/Apps/HelloWorld.html   - it works perfectly.

**Comment by Turbo87** [comment]
from what I know about that part of the codebase we are using an older version of Cesium. we might have to update it to make it work again.

**Comment by TobiasLohner** [comment]
They announced they would change the tile url when a specific release of 
cesium was published. I will look into the issue this week.

Am 2015-10-12 12:51, schrieb Tobias Bieniek:

**Comment by Turbo87** [comment]
awesome, thanks!

**Comment by nelg** [comment]
Does Cesium have a server component that can't be hosted on yourself.  From a quick grep, 
These two files:
skylines/frontend/static/js/ol-CesiumSwitcher.js
skylines/frontend/static/vendor/openlayers/cesium/Cesium/Cesium.js
seem to link back to cesiumjs.org.

Are you planning on fixing this by using their tile server, or including one in the skylines project, such as: https://github.com/geo-data/cesium-terrain-server

**Comment by Turbo87** [comment]
unfortuantely, we can't... see http://cesiumjs.org/data-and-assets/terrain/stk-world-terrain.html, specifically the "Terms of use" section.

**Comment by nelg** [comment]
OK, yeah, getting data like elevation data under an open license can be difficult / impossible.  That seems like the dependency would be on assets.agi.com, rather than cesiumjs.org.  Anyway, thanks for taking time to respond to this.  I'll take a look when you've had time to fix this, or someone else has picked it up.

**Comment by lordfolken** [comment]
We do have most of the srtm data for the xcsoar map server. The stuff from NASA and CIA is public domain. However we lack a webservice that could render this data. Do you know of such a service that can handel geotiff?

**Comment by TobiasLohner** [comment]
e392a55
