### ISSUE TITLE
skylines-project.org is expiring

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#421]
skylines-project.org is expiring by the end of the year. since we've been using skylines.aero for a while now this probably shouldn't be an issue.

@TobiasLohner do you see any reason to renew the old domain?

**Comment by lordfolken** [comment]
We should fix the following: 

git grep skylines-project.org
skylines/app.py:            'localhost', 'error@skylines-project.org',
skylines/frontend/views/users.py: http://www.skylines-project.org/users/recover?key=%x
tests/frontend/views/users_new_test.py:                 email=u'expect_error@skylines-project.org',
tests/frontend/views/users_new_test.py:    email = u'test_registration@skylines-project.org'
tests/frontend/views/users_new_test.py:    email = u'test_duplicates@skylines-project.org'

**Comment by lordfolken** [comment]
Also some configuration on the server:
root@www1:/etc# grep -R skylines-project.org *
nginx/sites-enabled/skylines.conf:  server_name skylines.duempel.org skylines.xcsoar.org *.skylines-project.org *.skylines.aero skylines.syhosting.ch;
nginx/sites-enabled/skylines.conf:  server_name api.skylines-project.org api.skylines.aero;
nginx/sites-enabled/skylines.conf:  server_name *.skylines-project.org skylines-project.org;
nginx/sites-enabled/skylines.conf:  ssl_certificate /home/skylines/ssl/skylines-project.org.crt;
nginx/sites-enabled/skylines.conf:  ssl_certificate_key /home/skylines/ssl/skylines-project.org.key;
nginx/sites-enabled/blog.conf:  server_name blog.skylines-project.org blog.skylines.aero;
grep: service/mapproxy-uwsgi: No such file or directory
grep: service/skylines-fastcgi: No such file or directory
grep: service/skylines-daemon: No such file or directory
grep: service/mapserver-fastcgi: No such file or directory
grep: service/celery-daemon: No such file or directory
skylines/serverumzug:  server_name skylines.duempel.org skylines.xcsoar.org *.skylines-project.org *.skylines.aero skylines.aero www.skylines-project.org;
skylines/serverumzug:  ssl_certificate /home/skylines/ssl/skylines-project.org.crt;
skylines/serverumzug:  ssl_certificate_key /home/skylines/ssl/skylines-project.org.key;
skylines/serverumzug:  server_name www.skylines-project.org skylines-project.org;
skylines/production.py:    ('localhost', 'error@skylines-project.org', ADMINS, 'SkyLines Error Report'))
skylines/nginx.conf:  server_name skylines.duempel.org skylines.xcsoar.org *.skylines-project.org *.skylines.aero skylines.syhosting.ch;
skylines/nginx.conf:  server_name api.skylines-project.org api.skylines.aero;
skylines/nginx.conf:  server_name *.skylines-project.org skylines-project.org;
skylines/nginx.conf:  ssl_certificate /home/skylines/ssl/skylines-project.org.crt;
skylines/nginx.conf:  ssl_certificate_key /home/skylines/ssl/skylines-project.org.key;
skylines/nginx.conf.bak:  server_name skylines.duempel.org skylines.xcsoar.org *.skylines-project.org *.skylines.aero skylines.aero www.skylines-project.org;
skylines/nginx.conf.bak:  ssl_certificate /home/skylines/ssl/skylines-project.org.crt;
skylines/nginx.conf.bak:  ssl_certificate_key /home/skylines/ssl/skylines-project.org.key;
skylines/nginx.conf.bak:  server_name www.skylines-project.org skylines-project.org;

**Comment by Turbo87** [comment]
I guess only the first two are actually relevant:

- skylines/app.py: 'localhost', 'error@skylines-project.org',
- skylines/frontend/views/users.py: http://www.skylines-project.org/users/recover?key=%x
