### ISSUE TITLE
Used to be able to sort flights

### ISSUE THREAD

**Issue by QuintS** [skylines-project/skylines#432]
But the feature is gone.

- Open a pilot's flight list
- Used to be able to sort based on distance, score and date
- Not possible anymore

**Comment by Turbo87** [comment]
@QuintS it's certainly coming back. I'm currently working on #431 and skipped that part for now.

**Comment by Turbo87** [comment]
this should work again, but it looks a bit different now

**Comment by QuintS** [comment]
Nice!
