### ISSUE TITLE
blog.skylines.aero still refers to www.skylines-project.org

### ISSUE THREAD

**Issue by QuintS** [skylines-project/skylines#433]
www.skylines-project.org non-existent. Maybe change or kill blog altogether.

**Comment by Turbo87** [comment]
thanks for reporting this! I pretty much forgot about that...

**Comment by Turakar** [comment]
Same for the IRC channel

**Comment by kerel-fs** [comment]
@Turbo87 Could you login to <https://freenode.net> and update the topic of #skylines?
