### ISSUE TITLE
airspace data needs update

### ISSUE THREAD

**Issue by bomilkar** [skylines-project/skylines#435]
I just noticed that airspace data for Germany is outdated. For instance EDR138, EDR144, EDR147.
How can this be updated to avoid false alarms?

**Comment by pyrog** [comment]
The airspaces are imported manually into the server database. See: [skylines/INSTALL.mapserver.md](https://github.com/skylines-project/skylines/blob/master/INSTALL.mapserver.md)

💡 I suggest to use CI for reloading automatically the DB when [airspace_list.txt](https://github.com/skylines-project/skylines/blob/master/mapserver/airspace/airspace_list.txt) is updated.

**Comment by bomilkar** [comment]
I don't know what triggered the original email below, however the
"aispace_list.txt" references a 2 year old airspace file for Germany
which is really outdated. (I don't know about the other countries.)

Who can change the list and replace the entry for de to:
http://www.daec.de/fileadmin/user_upload/files/2012/fachbereiche/luftraum/DAeC_Germany_Week22_2016.txt


Cheers,
Ronald

Am 31.10.2016 um 22:52 schrieb pyrog:

**Comment by pyrog** [comment]
I could do that, but is it better to parse the "up to date" (?) list from [xcsoar-data-repository](https://github.com/XCSoar/xcsoar-data-repository/blob/master/data/airspace.json) (See #538)

**Comment by TobiasLohner** [comment]
> :bulb: I suggest to use CI for reloading automatically the DB when airspace_list.txt is updated.

As written in #538 I don't recommend automation for updating airspaces.

**Comment by pyrog** [comment]
The automation could be _"send email to admins to build manually airspaces"_ 😉
