### ISSUE TITLE
Missing redirect to login page from /users/:id/{follow,unfollow}

### ISSUE THREAD

**Issue by dwlongs** [skylines-project/skylines#454]
Hi, when I was browsing the code and found a code error about login
the file path:
https://github.com/skylines-project/skylines/blob/master/skylines/frontend/views/user.py
from flask.ext.login import login_required
I think this is import error, request https://skylines.aero/users/79/follow failed. This import should use
from skylines.lib.decorators import login_required

**Comment by Turbo87** [comment]
good catch! indeed our own version of the decorator would more sense there.

to summarize: when you're not logged in and visit the `/users/:id/{follow,unfollow}` routes you see an error message, instead when using our own decorator you would get redirected to the login page.

@dwlongs can you open a pull request with that bugfix?

**Comment by dwlongs** [comment]
@Turbo87  good, I will later submit a pull request with this bugfix. I'm trying to understand this code detail, maybe able to join this project.

**Comment by Turbo87** [comment]
resolved by #493
