### ISSUE TITLE
.igc date (HFDTE) parsing incorrectly

### ISSUE THREAD

**Issue by keystoneclimber** [skylines-project/skylines#461]
When uploading .igc files, the date of the flight is displayed as 1 day prior.  For example when I upload an .igc file containing HFDTE250916, it displays as 09/24/2016

**Comment by Turbo87** [comment]
seems to work fine for most of my files. do you have an example file somewhere you can share?

**Comment by keystoneclimber** [comment]
[160925_ BrandonTarr_01.zip](https://github.com/skylines-project/skylines/files/504463/160925_.BrandonTarr_01.zip)

**Comment by Turbo87** [comment]
@keystoneclimber thanks, that helped! turns out the file was correctly parsed, but a bug in our code in combination with your timezone settings caused the browser to display a wrong date. this should be fixed once #462 is merged.

**Comment by keystoneclimber** [comment]
Sure thing.  Thanks!
