### ISSUE TITLE
retract sidebar by default on small screens

### ISSUE THREAD

**Issue by jharting** [skylines-project/skylines#469]
Having both the map and sidebar information works fine on normal devices. However, when I am on the phone and I open a someone's live tracking on skylines, I only see the sidebar spanning the entire screen by default. At that moment however, my intention always is to see where the pilot is on the map. (requires extra tap to hide the sidebar)

I think it would be helpful to have the sidebar retracted by default on devices with small screen size (leaving it open by default on normal devices).

**Comment by jharting** [comment]
![screenshot_20161011-204422](https://cloud.githubusercontent.com/assets/167352/19284210/3f23c1b4-8ff5-11e6-8774-5d159f6decb1.png)

**Comment by Turbo87** [comment]
resolved by #671

**Comment by jharting** [comment]
@Turbo87 thanks! I really appreciate this getting fixed.
