### ISSUE TITLE
French locale is not available

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#485]
All (?) translated messages in french are available but french language is not selectable in the UI:

- [skylines/ember/app/utils/locales.js](https://github.com/skylines-project/skylines/blob/master/ember/app/utils/locales.js)
- [skylines/skylines/frontend/translations/fr/LC_MESSAGES/messages.po](https://github.com/skylines-project/skylines/blob/master/skylines/frontend/translations/fr/LC_MESSAGES/messages.po)

Does something is missing ?

**Comment by Turbo87** [comment]
As you can see in https://github.com/skylines-project/skylines/blob/master/ember/translations/fr.yaml the French translation of the client-side code is still pretty empty, which is the reason why we disabled it for now. Would you be willing to help translating it to French?

**Comment by pyrog** [comment]
> which is the reason why we disabled it for now

OK :smile:

Is there other files that need translations ?
* https://github.com/skylines-project/skylines/blob/master/ember/translations/fr.yaml
* https://github.com/skylines-project/skylines/blob/master/skylines/frontend/translations/fr/LC_MESSAGES/messages.po

**Comment by Turbo87** [comment]
The first one is the relevant file now. The second one was for the server-rendered interface but we've transitioned away from that in the past few weeks. It is essentially unused but I've kept it in the repo for now as a reference.

**Comment by pyrog** [comment]
Ok, thank you for your explanations.

I made a first PR.
As I haven't any webserver installed on my computer, could you test it, please ?

**Comment by pyrog** [comment]
https://skylines.aero/about/imprint is not translated. (Also, I don't find the source file ?)

**Comment by Turbo87** [comment]
@pyrog yes, that's intentional

> Since SkyLines is running on a German server the imprint is written in German.

**Comment by pyrog** [comment]
Could you translate:

**Imprint**
Since SkyLines is running on a German server the imprint is written in German.

**Kontakt**

**Comment by Turbo87** [comment]
it's not possible at the moment, but I'll keep it in mind!

**Comment by pyrog** [comment]
Finish 😄 (miss just 5 sentences)

Could you check it and merge it please ?

**Comment by Turbo87** [comment]
@pyrog looks good! (see #503)
