### ISSUE TITLE
Template not translated

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#498]
https://github.com/skylines-project/skylines/blob/master/ember/app/templates/components/pin-button.hbs

```hbs
{{#if pinned}}
  <i class='icon-star icon-large'></i> Flight pinned!
{{else}}
  <i class='icon-star-empty icon-large'></i> Click to pin
{{/if}}
```

**Comment by Turbo87** [comment]
good catch! would you like to open a PR that fixes this issue?

**Comment by pyrog** [comment]
Founded another one:
https://github.com/skylines-project/skylines/blob/master/ember/app/templates/components/settings-panels/tracking-key.hbs#L13

**Comment by pyrog** [comment]
Found other:
* [ember/app/templates/flights.hbs#L7](https://github.com/skylines-project/skylines/blob/master/ember/app/templates/flights.hbs#L7)
* [ember/app/templates/ranking.hbs#L7](https://github.com/skylines-project/skylines/blob/master/ember/app/templates/ranking.hbs#L7)
* [ember/app/templates/search.hbs#L30](https://github.com/skylines-project/skylines/blob/master/ember/app/templates/search.hbs#L30)
* [ember/app/templates/timeline.hbs#L7](https://github.com/skylines-project/skylines/blob/master/ember/app/templates/timeline.hbs#L7)
* [ember/app/templates/tracking/index_loading.hbs#L8
](https://github.com/skylines-project/skylines/blob/master/ember/app/templates/tracking/index_loading.hbs#L8
)
