### ISSUE TITLE
"Stamen Terrain" base map

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#499]
The "Stamen [Terrain](http://maps.stamen.com/#terrain/7/44.575/7.663)" base map is available worldwide now and is IMHO looking pretty good. Since Mapbox, Bing and Google have usage limits we should investigate whether this base map can be used instead or in addition to the current options.

/cc @Harry-R

**Comment by Harry-R** [comment]
I have already done the implementation in bas-map.js, see https://github.com/Harry-R/skylines/commit/07f5a7fe120b18671118005f221e0678744f52e8
TODO: import the necessary parts of openlayers into the skylines project

**Comment by Turbo87** [comment]
> TODO: import the necessary parts of openlayers into the skylines project

this should now be possible (see #530)

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
