### ISSUE TITLE
Change Password Dialog current password prefilled

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#523]
Hello, 

When you go to the change password dialog the "current password" is filled out. This is not good practice, as someone accessing the browser can change the password without knowing the current one.
- Folken

**Comment by Turbo87** [comment]
hmm, that's true. do you know how to prevent filling that automatically?

**Comment by Turbo87** [comment]
looks like https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion is a simple solution for this

**Comment by Turbo87** [comment]
@lordfolken reading https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields it seems that this "feature" can't actually be turned off... 🤔
