### ISSUE TITLE
404 error page

### ISSUE THREAD

**Issue by Harry-R** [skylines-project/skylines#524]
When the user trys to access a page like [skylines.aero/tracking/not-existing](https://skylines.aero/tracking/not-existing), the correct error page is displayed, but when trying to access a page like [skylines.aero/not-existing](https://skylines.aero/not-existing) only a grey page without any content is displayed.

**Comment by Turbo87** [comment]
https://sentry.io/skylines/skylines/issues/175411374/

**Comment by Turbo87** [comment]
for reference on how to implement this: https://guides.emberjs.com/v2.9.0/routing/defining-your-routes/#toc_wildcard-globbing-routes
