### ISSUE TITLE
Select appropriate logo in maps according to Aircraft type

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#546]
See #543.

**Comment by Turbo87** [comment]
Are there any good symbols for paragliders?

**Comment by pyrog** [comment]
A stylized drawing like this but without pilots:
![images](https://cloud.githubusercontent.com/assets/2158081/19956395/6799c514-a18c-11e6-8994-a3cf8a221ae2.png) ![images-3](https://cloud.githubusercontent.com/assets/2158081/19956431/b88cb878-a18c-11e6-901d-9a257ea57f91.png)

See [livetrack24.com](http://www.livetrack24.com/track/778871) (their icon is not visible enough) but that's the idea.

**Comment by Turbo87** [comment]
the different is that their icon doesn't rotate in the flight direction so we can't really use that second icon

**Comment by pyrog** [comment]
We should design "nice" new SVG icons that could rotate 😄

**Comment by Turbo87** [comment]
@pyrog let me know once you have some icons ready 😉

**Comment by pyrog** [comment]
![glider_symbol](https://cloud.githubusercontent.com/assets/2158081/19964992/21a47a3e-a1c5-11e6-90b7-ffa3dd9b0f67.png)
![paraglider_symbol](https://cloud.githubusercontent.com/assets/2158081/19964993/21a8f51e-a1c5-11e6-958f-437508182918.png) Source: [Just One V1](http://www.trekking-parapentes.fr/images/produits/parapentes/justone/Just-one-rouge-noir-jaune.png)
![hang_glider_symbol](https://cloud.githubusercontent.com/assets/2158081/19966173/ef1bd7dc-a1ca-11e6-982c-352de7ff7f46.png) Source: [Wills Wing](http://www.delta-club-82.com/forum/uploads/post-1-1265887555.jpg)

@Turbo87 Here they are 😄

**Comment by Turbo87** [comment]
awesome! those look quite nice!

next problem now is that we don't know whether the flight is a glider flight, paraglider flight, etc. this is essentially blocked by #545

**Comment by pyrog** [comment]
> this is essentially blocked by #545

Yves, that why we should have a brainstorming on how to do this (in the point of view of the pilot)
