### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by Harry-R** [skylines-project/skylines#553]
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 53: ordinal not in range(128)`
Server throws 500, internal server error. 
See:  [Sentry](https://sentry.io/skylines/skylines/issues/176847673/)

URL to reproduce: https://skylines.aero/tracking/%C3%B6

**Comment by Turbo87** [comment]
https://sentry.io/skylines/skylines/issues/176847673/

**Comment by pyrog** [comment]
Is it really an issue for this URL?
The right part seem to be only an integer number 😉

But this could display a better error message:
* https://skylines.aero/tracking/name # word
* https://skylines.aero/tracking/123 # number (pilot ID not in db)

`Sorry!
It looks like there was error while loading this page. The error was automatically reported back to the developers. Please try again later!`

* https://skylines.aero/tracking/1234 # pilot ID in the db

`There is currently no live track of this pilot available.`

**Comment by Harry-R** [comment]
I think the problem is caused by the letters ö, ü and ä inside a URL, integers are no problem.

**Comment by Turbo87** [comment]
Problem is most likely that the python code expects a URL in Utf8 but is getting some other form of incompatible encoding

**Comment by Turbo87** [comment]
the server now correctly throws error 400 for this issue so I'm closing this. this was likely fixed by updating our Flask dependency.
