### ISSUE TITLE
XCSoar sim flight

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#560]
I started a sim flight:

1. It was displayed in [Live Tracking](https://skylines.aero/tracking) list. 
1. The glider was displayed on the [map](https://skylines.aero/tracking/6725), but didn't move.
1. It was located at my real position (my home in Jura) but on XCSoar Sim, it was at another aerodrome (in Savoie)

Is it a **XCSoar** or a **Skylines** issue?

I think that virtual flights shouldn't be displayed in Skylines.

**Comment by Turbo87** [comment]
This is not an issue in skylines. XCSoar should only send tracking fixes in fly mode, and unless they changed something that should already be the case.

**Comment by pyrog** [comment]
Add comment in XCSoar Trac http://bugs.xcsoar.org/ticket/3526#comment:3
