### ISSUE TITLE
Flights with strange values

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#575]
https://skylines.aero/flights/67671#tab-stats-total

Distance and speed are different in **Overview** and **Cruise performance** tabs.
Glide ration is completely 🤕 

**Overview**

Label | Value
--- | ---
Score | 0.0 pts.
Dist. | 0.0 km
Speed | 0.0 km/h

**Cruise performance**

Label | Value
--- | ---
ΔH	11 m
Distance	| 70,1 km
Avg. vario | 0,0 m/s
Avg. speed | 132,8 km/h
GR | **-6,375.2**

**Leg Statistics**
Seem to be complete weird

See [IGC](https://skylines.aero/files/2016-08-14-xcs-aaa-01_2.igc)

PS: if your [sort all flights by distance (descending)](https://skylines.aero/flights/all?column=distance&order=asc&page=4), you will find 4 pages of flights with no distance.
i.e. [Flight #56670](https://skylines.aero/flights/56670#tab-stats-phases) with a **-286.6 GR** !

**Comment by Turbo87** [comment]
my guess is that in this particular flight the takeoff and landing detection was wrong and so the scoring period wasn't large enough to count anything. the cruise performance data might include the times outside the scoring time window too.

**Comment by Turbo87** [comment]
Glide Ratio is completely fine since this was a motor glider flight and the flight started lower than it ended

**Comment by pyrog** [comment]
_"The glide ratio, which is the ratio of an (**unpowered**) aircraft's forward motion to its descent"_
Source: https://en.wikipedia.org/wiki/Lift-to-drag_ratio

Should it be calculated when the engine if off?

**Comment by Turbo87** [comment]
yes, that would probably make sense. but that part of the calculation is done by the XCSoar code, so I'm going to close this issue here because they have their own issue tracker and at this point there's not much I can do about it.

**Comment by pyrog** [comment]
Got another with high GR. It's not a glider, it's a 🚀 
<img width="399" alt="Glide ratio of 519" src="https://cloud.githubusercontent.com/assets/2158081/20359125/be7b6dd6-ac2e-11e6-8718-648450727818.png">

Source: [Flights 48503](https://skylines.aero/flights/48503/#tab-stats-phases)

**Comment by Turbo87** [comment]
a GR like that is not unusual if you're flying along cloud streets in a glider
