### ISSUE TITLE
ASH 31 Mi type is motorglider

### ISSUE THREAD

**Issue by pyrog** [skylines-project/skylines#577]
source: http://www.alexander-schleicher.de/en/flugzeuge/ash-31-mi/

https://skylines.aero/api/aircraft-models
```json
{
  "models": [
    {
      "id": 283,
      "name": "ASH 31 Mi 18m",
      "index": 118,
      "type": "glider"
    },
    {
      "id": 16,
      "name": "ASH 31 Mi 21m",
      "index": 121,
      "type": "glider"
    },
  ]
}
```

**Comment by Turbo87** [comment]
what we call `motorglider` in the API is actually a touring motorglider (TMG), while the ASH 31 Mi is mainly a glider with a retractable engine.

**Comment by pyrog** [comment]
> he ASH 31 Mi is mainly a glider with a retractable engine.

I understood, but for my point of view, the difference between both is… the motor :wink:
So the flight analysis could take care of this "detail" ?

**Comment by Turbo87** [comment]
I have to admit that I'm not sure what initially caused us to differentiate it in this way, but we would certainly have to adjust *all* motorgliders then, not just the ASH 31, and I'm not sure right now what other implications that would have.

**Comment by pyrog** [comment]
>we would certainly have to adjust all motorgliders then, not just the ASH 31

Of course, but as I'am not a pilot I don't know all the gliders model 😉 
I wrote this issue to notice that point and don't forget it.

I plan to add a link to web pages for each model (manufacturer, wikipedia…), 
e.g.

- manufacturer http://www.alexander-schleicher.de/en/flugzeuge/ash-31-mi/
- drawing http://www.alexander-schleicher.de/wp-content/uploads/2015/03/31-3S-Ansicht.jpg

So I could check at the same time if there is a motor in the glider.

**Comment by Turbo87** [comment]
Actually in the long term I'd like to move away from the fixed `aircraft-models` list. Instead each pilot should be able to create a list of aircraft including their registration, competition ID, model, etc. and then choose from that list during flight-upload.

**Comment by pyrog** [comment]
> Actually in the long term I'd like to move away from the fixed aircraft-models list. 

👍 

The point is that it could be rapidly a mess. So it need a "moderation" process to clean the list if needed.

The list could be a json/csv file in a GitHub repository ?
Your backend (and software from other project) could just load it once a day.

**Comment by pyrog** [comment]
I suggest to add an item `[Ask a new aircraft model]` in the list.

So a user as just to select this special item (that could be translated), and the backend could create a new request in GitHub (or just send an email).
We could imagine a backend task that select the appropriate model after is creation.

**PS:** I suggest also to add `[Generic paraglider]`, `[Generic  hangglider]`… to this list.

The IGC model is stored in the database:
https://skylines.aero/api/flights/12345
```json
{
  "flight": {
    "id": 12345,
```
…
```json
    },
    "model": {
      "id": 290,
      "name": "ASW 19",
      "index": 100,
      "type": "glider"
    },
```
…
```json
    "igcFile": {
```
…
```json
      "filename": "25hgrmb1.igc",
      "registration": "D-3841",
      "competitionId": "WD",
      "model": "ASW 19",
      "date": "2012-05-17"
    }
  }
}
```
