### ISSUE TITLE
Access not allowed on first set up

### ISSUE THREAD

**Issue by asnair** [skylines-project/skylines#600]
So I saw skylines recently and wanted to see what running my own system looked like, finally got everything installed, but now the server is refusing to connect. At first it was a 403 which I fixed by editing the apache2.conf file, but this next error seems more specific to skylines and I don't see it addressed anywhere:

![Service refused to connect](https://gyazo.com/88ea1c480e41ec11cf5e284c74d737d5.png)
I'm not sure where the setting would be to allow connection. It's currently in debug mode, as it's the first time running ./manage.py runserver and it says

`*Debugger is active!`
`*Debuger pin code: 123-456-789`

It also says it's running on http:/0.0.0.0:5000/, which on 127.0.0.1:5000 shows a 404 Not Found. I'm not sure what's intended behavior, but from the INSTALL.md I got the impression that what's been done so far should be enough to have it running. Help is greatly appreciated :) I'll continue working on it and update if I figure it out. Thanks!

**Comment by Turbo87** [comment]
@asnair I'm assuming you followed the steps at https://github.com/skylines-project/skylines/blob/master/INSTALL.md?

unfortunately that document is a little outdated and I just noticed right now that it needs an update.

in the meantime you can try to follow the steps in https://github.com/skylines-project/skylines/blob/master/Vagrantfile and see if that works for you. if you have any specific questions please let me know!

**Comment by asnair** [comment]
Correct I did follow the INSTALL.md file, although I discovered it was outdated and started figuring it out as I went, I was actually going to update the INSTALL file based on what I figured out along the way.

Would you know if the error seen in the picture is due to apache or flask? I'm not very familiar with either of the 2, and don't know where to look to discover what's causing the server refusal.

**Comment by Turbo87** [comment]
> I was actually going to update the INSTALL file based on what I figured out along the way.

that would be awesome, thanks!

> Would you know if the error seen in the picture is due to apache or flask?

that doesn't look like flask. why did you use Apache? it isn't necessary if you just want to develop on the project on your own machine.

**Comment by asnair** [comment]
I'll definitely update the INSTALL file when I figure everything out!
And I had a flask project on the same box with apache from before. I'll start with a clean box and redo, should be faster this time anyway, you can basically run manage.py over and over and it tells you what's missing. I'm aiming for updating the INSTALL by End of Day Sunday.

**Comment by Turbo87** [comment]
@asnair there is one major difference to a "normal" flask app. In the current state the flask app only provides a JSON-based API, but the frontend is provided by an [Ember.js](http://emberjs.com/) app that you can find in the `ember` subfolder. If you want to just work on the frontend you can use your local development version but talk to the real API server at skylines.aero by running `ember serve --proxy https://skylines.aero` from the `ember` subfolder (after `npm install && bower install` to install the JS dependencies).

**Comment by Turbo87** [comment]
@asnair any updates? do you need more help?

**Comment by asnair** [comment]
@Turbo87 sorry for the delay, something came up but I'm on it now and will update if I run into problems or when I get it up. I'm writing the steps as I go and hopefully should have the INSTALL done soon. I wasn't sure if the install/setup for Postgres should be explained in the file, as it's harder to find on the Postgres site, and would make readability easier if everything someone had to do was contained in a single README/INSTALL file.

**Comment by Turbo87** [comment]
> I wasn't sure if the install/setup for Postgres should be explained in the file, as it's harder to find on the Postgres site, and would make readability easier if everything someone had to do was contained in a single README/INSTALL file.

The problem with this is that depending on your Operating System the instructions might differ, so I'd prefer it if we just linked to the official documentation instead.

Also for now the recommended approach is using the existing Vagrant setup for serverside development which should include all the necessary steps to setup the Postgres DB inside the VM.
