### ISSUE TITLE
download igc does not work

### ISSUE THREAD

**Issue by GliderGeek** [skylines-project/skylines#601]
Downloading an igc file does not seem to work
- Mac OS 10.12
- Firefox 51.0.1 (64bit)
- For instance this one: https://skylines.aero/flights/20237
<img width="405" alt="screen shot 2017-02-05 at 23 32 53" src="https://cloud.githubusercontent.com/assets/16109193/22630491/70234f66-ebfb-11e6-87a3-f5ab19ede3c8.png">

**Comment by Turbo87** [comment]
interesting, thanks for reporting that!

**Comment by Turbo87** [comment]
https://github.com/skylines-project/skylines/blob/master/ember/app/templates/components/flight-details-table.hbs#L168 looks correct on first glance but it seems that https://github.com/intercom/ember-href-to is redirecting that link to the client-side app, which has no knowledge of that route... 🤔 

from their README it seems like a `data-href-to-ignore` might be able to fix this
