### ISSUE TITLE
API interface for external access

### ISSUE THREAD

**Issue by acasadoalonso** [skylines-project/skylines#605]
Folks,
I wonder if there is a published API in order to access the tracking data of an specific glider (knowing their live tracking key) , so it could be integrated on some other tracking systems, like OGN, etc. ...
Thanks in advance.
AC/.

**Comment by Turbo87** [comment]
@acasadoalonso there is an API, but it is not "published" yet unfortunately. I'll let you know once it is stable enough to be used by others.

The current live tracking data can be accessed at https://skylines.aero/api/live

**Comment by Turbo87** [comment]
#226 tracks the progress of defining a Public API
