### ISSUE TITLE
vagrant: Can't get the dev environment running

### ISSUE THREAD

**Issue by kerel-fs** [skylines-project/skylines#606]
## Steps to reproduce:
1. Setup the skylines vm and start the flask app
```
vagrant up
vagrant ssh
cd /vagrant
./manage.py runserver
```
2. Try to access the frontend in the browser (<http://localhost:5000>)

Result:
```
IOError: [Errno 2] No such file or directory: '/vagrant/skylines/frontend/static/index.html'
```

What step is missing here?
Afair some time ago it worked exactly this way/I filed PR to the Vagrantfile to make it work.

PS: For now I'm only interested in backend development, thus I guess this node-foo isn't required, is it?

edit:
PPS: Actually I'm not sure I'd like to contribute to this node-foo at all, nevertheless I'd like to contribute the required backend code for the ogn integration. :)

**Comment by Turbo87** [comment]
@kerel-fs sorry, I should've documented that better... 😞 

I think #600 is more or less a duplicate

> What step is missing here?

run `node_modules/.bin/ember build` in the `ember` subfolder. this will build the frontend application into `/vagrant/skylines/frontend/static/` and then you will be able to reach it at http://localhost:5000/

> PS: For now I'm only interested in backend development, thus I guess this node-foo isn't required, is it?

it is required to build it once, unless you only want to use the API endpoints. in that case the server should work fine without those files available.

> PPS: Actually I'm not sure I'd like to contribute to this node-foo at all, nevertheless I'd like to contribute the required backend code for the ogn integration. :)

that would be cool, thanks :)

let me know if you have any other questions.

**Comment by kerel-fs** [comment]
Ok, this should be feasible.

Unfortunately `node_modules/.bin/ember` isn't available in the dev vm.
Is it required to install node/ember on my host machine?

**Comment by Turbo87** [comment]
Hmm strange, try running `npm install` inside the ember folder to install the necessary dependencies first. I thought that was done automatically.

**Comment by kerel-fs** [comment]
You removed it with
https://github.com/skylines-project/skylines/commit/6b6e9fd9d20faba0674971db4d251f257b660b89

**Comment by Turbo87** [comment]
Good point :joy:

**Comment by kerel-fs** [comment]
Running the commands removed in https://github.com/skylines-project/skylines/commit/6b6e9fd9d20faba0674971db4d251f257b660b89 did work, so we should either add them as another manual step to the installation instructions or revert this commit. @Turbo87, any preference?

**Comment by Turbo87** [comment]
The main reason for the vagrant environment was to allow development on non-linux machines where the native xcsoar code doesn't run. That code is not needed for the front end though, which can be developed on any platform. Since the front end build is pretty slow inside the VM I recommend to not use vagrant for that and only use it for backend development.
