### ISSUE TITLE
translation errors in Dutch

### ISSUE THREAD

**Issue by GliderGeek** [skylines-project/skylines#637]
for example:

>  Database Vluchten
> upload U IGC bestanden en deel ze met U vrienden. We veranderen U bestanden niet, of > belemmeren U niet ze terug te downloaden!

'U' should be 'uw' or 'jouw'/'je'

furthermore:
Upload (EN) is not Opladen (dutch)

**Comment by Turbo87** [comment]
we are using https://lingohub.com for translations. if you send me you mail address I can invite you to the SkyLines org there. I would be awesome if you could fix this. alternatively you could also fix this directly in the translations file (https://github.com/skylines-project/skylines/blob/master/ember/translations/nl.yaml)

**Comment by GliderGeek** [comment]
will do this directly in the translations yaml and open a new pull request.
browsing through there i see a lot of translation which i think can be improved. 
maybe @roeles can have a look to see whether he agrees with the suggested changes?

**Comment by Turbo87** [comment]
> will do this directly in the translations yaml and open a new pull request.

that would be awesome, thanks a lot! btw you can run the frontend locally with the live backend using `ember serve --proxy=https://skylines.aero` and I just remembered that I need to document this properly... 😞

**Comment by GliderGeek** [comment]
could you invite me to lingohub? i heard from Roel that he has made some changes there
will send you an email such that you have my address

**Comment by Turbo87** [comment]
cool, thanks. I've sent you an invitation. let me know if you need help with anything!

**Comment by GliderGeek** [comment]
worked through the complete translation and have applied some alteration.
will discuss some of them with @roeles inside lingohub and will report here when this is done

**Comment by Turbo87** [comment]
awesome, thanks a lot!!

**Comment by GliderGeek** [comment]
This was not yet done. Just finished editing the 'u' and 'uw' entries.
Think it is in quite good shape now

**Comment by Turbo87** [comment]
Sorry, thought you were done. I'll export the data from LingoHub again. It's only a single click on a button after all :)
