### ISSUE TITLE
Erroneous computation of powered phase

### ISSUE THREAD

**Issue by Adrien81** [skylines-project/skylines#642]
When take-off in a circling pattern is followed by a circling phase :
https://skylines.aero/flights/74525#tab-stats-phases
click on first phase.
![image](https://cloud.githubusercontent.com/assets/921423/25565172/db455d44-2dc2-11e7-8346-4559e68eab55.png)

**Comment by Turbo87** [comment]
Hi @Adrien81! We are using the flight analysis code of XCSoar for this feature so it would be best if you could open an issue on their issue tracker since there is unfortunately not much we can do about it from our side.

**Comment by Adrien81** [comment]
Done!
https://bugs.xcsoar.org/ticket/3843#ticket

**Comment by Adrien81** [comment]
apf suggests a manual override of the end of powered phase, as reportedly allowed by the IGC.
