### ISSUE TITLE
start- and finish time not visible in dutch

### ISSUE THREAD

**Issue by GliderGeek** [skylines-project/skylines#646]
This is dutch:

<img width="404" alt="screen shot 2017-05-05 at 12 51 39" src="https://cloud.githubusercontent.com/assets/16109193/25742836/a214b1fa-3191-11e7-8a2f-41c94ee3dfd6.png">

This is english:

<img width="393" alt="screen shot 2017-05-05 at 12 52 20" src="https://cloud.githubusercontent.com/assets/16109193/25742846/b397de70-3191-11e7-836e-8c42de96e42a.png">

[this flight](https://skylines.aero/flights/74840)
problem only occurs at dutch language

**Comment by Turbo87** [comment]
interesting. looks like a bug in the Dutch translation file.

**Comment by GliderGeek** [comment]
this is what i see in lingohub: is this maybe the source of error?

<img width="852" alt="screen shot 2017-05-05 at 13 05 25" src="https://cloud.githubusercontent.com/assets/16109193/25743217/914372ba-3193-11e7-918e-286a7a680d52.png">

**Comment by Turbo87** [comment]
yeah, the `{time}` token seems to be missing

**Comment by Turbo87** [comment]
for more info on the ICU message format that we use for translations here, have a look at https://format-message.github.io/icu-message-format-for-translators/

**Comment by GliderGeek** [comment]
also {airport} should be there instead of vliegveld?

**Comment by Turbo87** [comment]
> also {airport} should be there instead of vliegveld?

yep

**Comment by GliderGeek** [comment]
has been changed in lingohub
