### ISSUE TITLE
Ground level chart not displayed

### ISSUE THREAD

**Issue by Harry-R** [skylines-project/skylines#649]
The ground level chart is not displayed at all.
![skylines_ground_chart](https://cloud.githubusercontent.com/assets/7561362/25862301/dd53a2a4-34e7-11e7-9341-8cfc329eda3a.png)

**Comment by Turbo87** [comment]
@Harry-R to clarify, is this just for live tracking or also for post-flight display?

**Comment by Harry-R** [comment]
It is also for post-flight display
