### ISSUE TITLE
Is the Skylines App Using Barometric Sensors????

### ISSUE THREAD

**Issue by JBlyth** [skylines-project/skylines#677]
It seems that the Android App for Skylines doesn't support the barometric sensors that many phones have. 

Are there any plans to make use of the barometric data. It would make aviation altitudes much more accurate....

Cheers
John

**Comment by Turbo87** [comment]
> Android App for Skylines

sorry, I don't know what you are talking about. there is no "Android App for Skylines".

**Comment by JBlyth** [comment]
This one
https://play.google.com/store/apps/details?id=ch.luethi.skylinestracker

**Comment by Turbo87** [comment]
that is not an official Skylines project. you should contact the author of that app about this.

**Comment by JBlyth** [comment]
Thanks, will do....
