### ISSUE TITLE
Docker development environment?

### ISSUE THREAD

**Issue by iamambrus** [skylines-project/skylines#695]
Did anybody put together a docker environment of Skylines? There are quite some prerequisites to install it, would make getting involved significantly easier.

**Comment by Turbo87** [comment]
@iamambrus not that I'm aware of, but we do have a [Vagrantfile](https://github.com/skylines-project/skylines/blob/master/Vagrantfile) which serves a somewhat similar purpose.

**Comment by Turbo87** [comment]
also worth mentioning that for frontend development you don't need as much prerequisites and you can just use the live backend server for that. only when you want to work on the backend too you will need a few more things installed.
