### ISSUE TITLE
"Live" icon is missing

### ISSUE THREAD

**Issue by lordfolken** [skylines-project/skylines#700]
When one uses a smaller resolution, the text labels are replaced by icons. These icons are all there except the live icon, which is just a black box.

**Comment by Turbo87** [comment]
<img width="387" alt="bildschirmfoto 2017-11-12 um 10 28 11" src="https://user-images.githubusercontent.com/141300/32697592-367e8a6c-c794-11e7-9c3b-386c43aafc1b.png">

seems to work fine for me 🤔

**Comment by QuintS** [comment]
Works OK for me too
