### ISSUE TITLE
Poor font rendering on Windows

### ISSUE THREAD

**Issue by keystoneclimber** [skylines-project/skylines#711]
Chrome browser on Windows 7 renders the default font pretty poorly, especially s, 2, & 5 looks very thin to almost non-existent...
![screenshot001](https://user-images.githubusercontent.com/1234508/35545442-1eccc6c2-053d-11e8-9948-0674d10efbea.png)
![screenshot002](https://user-images.githubusercontent.com/1234508/35545446-2538c16e-053d-11e8-8f18-4f25e10a8fc5.png)

**Comment by Turbo87** [comment]
Ouch, I didn't know. Thanks for making me aware of this!

**Comment by Turbo87** [comment]
This should be fixed now, please let me know if you still see any problems like this!

**Comment by keystoneclimber** [comment]
Looks much better.  Will do, thanks!

Brandon

On Fri, Feb 9, 2018 at 1:58 PM, Tobias Bieniek <notifications@github.com<mailto:notifications@github.com>> wrote:

This should be fixed now, please let me know if you still see any problems like this!
