### ISSUE TITLE
Slovak airspaces out of date

### ISSUE THREAD

**Issue by kapitan-iglu** [skylines-project/skylines#896]
Slovak airspaces are invalid. How can I update them to actual state? I have recent definitions in openair format (valid from 29 MAR 2018).

**Comment by Turbo87** [comment]
@kapitan-iglu do you have a link to the new airspace file?

**Comment by kapitan-iglu** [comment]
Unfortunately not. There is no official slovak web page with actual air space files.

Attached file  [LZBB20180329.txt](https://github.com/skylines-project/skylines/files/2172776/LZBB20180329.txt) was created by hand from [eAIP](https://aim.lps.sk/web/?fn=200&lng=en) data by chief of Slovak gliding commission. This process of creation repeats every year and I'm trying to automate it. All official gliding events/competitions are using this file. (there is also SeeYou CUB file available if needed)

There is another source of air space definitions on [openflightmaps.org](https://openflightmaps.org/live/lz-slovakia/), scroll down to section Data and choose file format to download. Source of this data is again the same - slovak eAIP parsed semi-automatically and uploaded to openflightmaps.

@Turbo87: Are this data reliable enough for you to use it on skyines?

**Comment by Turbo87** [comment]
done

**Comment by kapitan-iglu** [comment]
Thaks, now airspaces looks real :)

Is there any way to keep air space information in skylines up to date? Is there (on skylines side) any mechanism available to update air space definition (automatically)?
