### ISSUE TITLE
Psycopg2 dependency update choice

### ISSUE THREAD

**Issue by kerel-fs** [skylines-project/skylines#897]
Currently the following warning is shown when starting any module with a `psycopg2` dependendcy:

> \>\>\> import psycopg2
> /home/vagrant/.local/share/virtualenvs/vagrant-gKDsaKU3/local/lib/python2.7/site-packages/psycopg2/\_\_init\_\_.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

Starting with Psycopg 2.7.4, they are releasing two different packages on PyPI: psycopg2 and psycopg2-binary. The choices for us are two now (src: [Release Note](http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/)):
- if the program works fine with the Wheel packages, and the convenience of the binary distribution is preferred, it is possible to specify the dependency on the binary package using the `psycopg2-binary` instead of the `psycopg2` PyPI package. No change to the program code is needed;
- if there are concerns about the unreliability of the Wheels package, it is adviced to force installation from source. This requires the presence of build tools and runtime libraries on the client, but again it requires no change to the code.

The second solution (installation from source) would require us to ignore this message until psycopg 2.8 is released, because `pipenv` doesn't support `--no-binary` natively (see pypa/pipenv#1430).
What should we do?

**Comment by Turbo87** [comment]
I'm currently undecided on this topic. I've read up on it when I first encountered the warning and the people in their issues couldn't make up their mind if this was a good change or not. For now my plan was to ignore the warning until the dust has settled and the maintainers have made up their mind.

**Comment by mongrelion** [comment]
> For now my plan was to ignore the warning until the dust has settled and the maintainers have made up their mind.

@Turbo87 do you think that the dust has settled now? do we have enough information to move forward? is this still something we want? otherwise I propose to close this PR.

**Comment by Turbo87** [comment]
> The second solution (installation from source) would require us to ignore this message until psycopg 2.8 is released

https://github.com/skylines-project/skylines/blob/master/Pipfile#L19 says that we are using v2.8 now, so I guess we can indeed close this.
