### ISSUE TITLE
Add Js3 to list of aircraft

### ISSUE THREAD

**Issue by roeles** [skylines-project/skylines#914]
We have the first Js3 flight in the database:
https://skylines.aero/flights/89848

**Comment by Turbo87** [comment]
I talked to Peter via Facebook about this already.

Handicaps according to https://www.daec.de/fileadmin/user_upload/files/2018/Sportarten/Segelflug/DMSt-WO_2018ki.pdf:

121 (18m) and 116 (15m)

**Comment by Turbo87** [comment]
```
./manage.py aircraft add_model -k 1 -i 121 "JS 3 18m"
./manage.py aircraft add_model -k 1 -i 116 "JS 3 15m"
```

done!
