### ISSUE TITLE
Finnish airspace is obsolete

### ISSUE THREAD

**Issue by lkangas** [skylines-project/skylines#964]
Finnish airspace is from 2011. New one is uploaded here:

https://github.com/XCSoar/xcsoar-data-content/blob/master/airspaces/Finland_airspace_2018-05-24.txt

**Comment by lkangas** [comment]
Now at a fixed url. 

http://download.xcsoar.org/airspaces/Finland_airspace_2018-05-24.txt

**Comment by Turbo87** [comment]
should be updated now
